spring:
  application:
    name: healthyme-personal
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:healthyme_personal_db}?useSSL=${DB_USE_SSL:false}&serverTimezone=UTC
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:}
    hikari:
      connection-timeout: 2000
      maximum-pool-size: 5
  jpa:
    show-sql: ${SHOW_SQL:true}
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
    open-in-view: false

# Configuración Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always