spring:
  application:
    name: healthyme-personal
  datasource:
    url: jdbc:mysql://localhost:3306/healthyme_personal_db?useSSL=false&serverTimezone=UTC
    username: root
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        format_sql: true
    open-in-view: false