server:
  port: 8761
  shutdown: graceful

spring:
  application:
    name: discovery-server

eureka:
  instance:
    hostname: discovery-server
    prefer-ip-address: false
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
  server:
    enable-self-preservation: true
    renewal-percent-threshold: 0.85
    eviction-interval-timer-in-ms: 60000
    response-cache-update-interval-ms: 30000
    response-cache-auto-expiration-in-seconds: 180
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

# Métricas y monitoreo para producción
management:
  endpoints:
    web:
      exposure:
        include: ["health", "info", "metrics"]
  endpoint:
    health:
      show-details: when-authorized

# Logging para producción
logging:
  level:
    root: WARN
    com.netflix.eureka: INFO
    com.netflix.discovery: INFO
    org.springframework.cloud: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"