spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config
        default-profile: native
        git:
          skip-ssl-validation: true
          default-label: main

# Server configuration
server:
  port: 8888
  shutdown: graceful

# Monitoring y métricas para producción
management:
  endpoints:
    web:
      exposure:
        include: ["health", "info", "refresh"]
  endpoint:
    health:
      show-details: when-authorized
  security:
    enabled: false

# Logging para producción
logging:
  level:
    root: WARN
    org.springframework.cloud: INFO
    org.springframework.boot: WARN
    org.springframework.cloud.config: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
    initial-instance-info-replication-interval-seconds: 40
    instance-info-replication-interval-seconds: 30
  instance:
    prefer-ip-address: true
    hostname: config-server
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90