server:
  port: 8080
  shutdown: graceful

spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true

      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: healthyme-storage
          uri: lb://healthyme-storage
          predicates:
            - Path=/api/storage/**
          filters:
            - name: CircuitBreaker
              args:
                name: storageServiceCircuitBreaker
                fallbackUri: forward:/fallback/storage
        - id: notification-service
          uri: lb://healthyme-notification
          predicates:
            - Path=/api/notificaciones/**
          filters:
            - name: CircuitBreaker
              args:
                name: notificationServiceCircuitBreaker
                fallbackUri: forward:/fallback/notification
        - id: healthyme-pacientes-service
          uri: lb://healthyme-pacientes
          predicates:
            - Path=/api/v1/pacientes/**
          filters:
            - name: CircuitBreaker
              args:
                name: pacientesCircuitBreaker
                fallbackUri: forward:/fallback/pacientes

        - id: healthyme-citas
          uri: lb://healthyme-citas
          predicates:
            - Path=/api/citas/**

        - id: healthyme-laboratorio
          uri: lb://healthyme-laboratorio
          predicates:
            - Path=/api/**

        - id: healthyme-payment
          uri: lb://healthyme-payment
          predicates:
            - Path=/payment/api/**

        - id: healthyme-personal
          uri: lb://healthyme-personal
          predicates:
            - Path=/api/medicos/**

# Resilience4j configuration
resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 10s
        failureRateThreshold: 50
        slowCallRateThreshold: 50
        slowCallDurationThreshold: 2s
        eventConsumerBufferSize: 10
    instances:
      storageServiceCircuitBreaker:
        baseConfig: default
        waitDurationInOpenState: 15s  # tiempo para servicios que manejan archivos
      notificationServiceCircuitBreaker:
        baseConfig: default
        failureRateThreshold: 60  # tolerante con el servicio de notificaciones
      pacientesCircuitBreaker:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
        recordExceptions:
          - java.io.IOException
          - java.util.concurrent.TimeoutException
          - org.springframework.web.client.HttpServerErrorException
          - java.net.ConnectException
  timelimiter:
    instances:
      storageServiceCircuitBreaker:
        timeoutDuration: 10s  # timeout para operaciones de archivos
      notificationServiceCircuitBreaker:
        timeoutDuration: 5s
      pacientesCircuitBreaker:
        timeoutDuration: 3s

# Metrics and monitoring
management:
  endpoints:
    web:
      exposure:
        include: ["health", "info", "metrics", "prometheus", "circuitbreakerevents"]
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true
    ratelimiters:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
  info:
    env:
      enabled: true

# Logging
logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: DEBUG
    org.springframework.security: INFO
    reactor.netty: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"