spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?createDatabaseIfNotExist=true
    username: ${DB_NAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 15
      minimum-idle: 5
      idle-timeout: 300000
      max-lifetime: 1200000
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none

  jackson:
    default-property-inclusion: non_null
    property-naming-strategy: SNAKE_CASE
    time-zone: America/Lima

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka-prod-1:9092,kafka-prod-2:9092,kafka-prod-3:9092}
    consumer:
      group-id: consultas-service-prod
      auto-offset-reset: latest

logging:
  level:
    root: WARN
    dev.Elmer: INFO
    org.springframework: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: /var/log/healthyme/consultas.log
    max-size: 10MB
    max-history: 7

resilience4j:
  circuitbreaker:
    instances:
      recetaService:
        failureRateThreshold: 40
        waitDurationInOpenState: 30s
        slidingWindowSize: 20
      pacienteService:
        failureRateThreshold: 40
        waitDurationInOpenState: 30s
      medicoService:
        failureRateThreshold: 40
        waitDurationInOpenState: 30s

  timelimiter:
    instances:
      recetaService:
        timeoutDuration: 10s
      pacienteService:
        timeoutDuration: 10s
      medicoService:
        timeoutDuration: 10s