server:
  port: 8087
  shutdown: graceful

spring:
  jackson:
    default-property-inclusion: non_null
    property-naming-strategy: SNAKE_CASE
    time-zone: America/Lima
  datasource:
    url: jdbc:mysql://${DB_HOST:mysql}:${DB_PORT:3306}/${DB_NAME:healthyme_storage}?createDatabaseIfNotExist=true
    username: ${DB_USER_DEV:root}
    password: ${DB_PASSWORD_DEV:j0s33nr1qu3}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  servlet:
    multipart:
      max-file-size: ${storage.max-file-size}
      max-request-size: ${storage.max-file-size}

storage:
  location: ${STORAGE_LOCATION:./storage/files}
  max-file-size: 10MB
  max-capacity-mb: 1024
  allowed-content-types: >
    image/jpeg,image/png,image/gif,application/pdf,
    application/msword,application/vnd.openxmlformats-officedocument.wordprocessingml.document,
    application/vnd.ms-excel,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,circuitbreakers
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true

resilience4j:
  circuitbreaker:
    instances:
      fileOperationBreaker:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 15s
        failureRateThreshold: 50
        recordExceptions:
          - java.io.IOException
          - java.lang.RuntimeException
      dbOperationBreaker:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 10s
        failureRateThreshold: 50
        recordExceptions:
          - org.springframework.dao.DataAccessException
          - java.sql.SQLException
  timelimiter:
    instances:
      fileOperationBreaker:
        timeoutDuration: 10s
      dbOperationBreaker:
        timeoutDuration: 5s