spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/healthyme_notification?createDatabaseIfNotExist=true
    username: ${DB_USER_DEV}
    password: ${DB_PASSWORD_DEV}
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update

  # MailHog proximamente
  #mail:
  #  host: localhost
  #  port: 1025
  #  username: dev
  #  password: dev
  #  properties:
  #    mail:
  #      smtp:
  #        auth: false
  #        starttls:
  #          enable: false

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  # Kafka local
  kafka:
    bootstrap-servers: localhost:9092

logging:
  level:
    root: INFO
    studio.devbyjose: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG

resilience4j:
  circuitbreaker:
    instances:
      emailService:
        waitDurationInOpenState: 10s
        failureRateThreshold: 70  # Más tolerante
      storageService:
        failureRateThreshold: 70