spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/healthyme_consultas?createDatabaseIfNotExist=true
    username: ${DB_USER_DEV}
    password: ${DB_PASSWORD_DEV}
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update

  jackson:
    default-property-inclusion: non_null
    property-naming-strategy: SNAKE_CASE
    time-zone: America/Lima

  kafka:
    bootstrap-servers: localhost:9092

logging:
  level:
    root: INFO
    dev.Elmer: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG

resilience4j:
  circuitbreaker:
    instances:
      recetaService:
        waitDurationInOpenState: 8s
        failureRateThreshold: 60
      pacienteService:
        waitDurationInOpenState: 6s
        failureRateThreshold: 60
      medicoService:
        waitDurationInOpenState: 6s
        failureRateThreshold: 60

  timelimiter:
    instances:
      recetaService:
        timeoutDuration: 5s
      pacienteService:
        timeoutDuration: 5s
      medicoService:
        timeoutDuration: 5s

  retry:
    instances:
      recetaRetry:
        maxAttempts: 3
        waitDuration: 1s
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2