spring:
  application:
    name: healthyme-reclamaciones
  jackson:
    default-property-inclusion: non_null
    property-naming-strategy: SNAKE_CASE
    time-zone: America/Lima
    serialization:
      write-dates-as-timestamps: false
    date-format: yyyy-MM-dd HH:mm:ss
  datasource:
    url: jdbc:mysql://mysql:3306/healthyme_reclamaciones?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: j0s33nr1qu3
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8091
  shutdown: graceful

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    hostname: healthyme-reclamaciones

feign:
  client:
    config:
      default:
        connect-timeout: 5000
        read-timeout: 10000

healthyme:
  reclamaciones:
    notification:
      enabled: true
      cliente:
        habilitado: true
      interno:
        habilitado: true
      url-base: "https://healthyme.com/reclamaciones"
    plantillas:
      recepcion: 1
      cambio-estado: 2
      nueva-respuesta: 3
      cierre: 4
      asignacion: 5
      escalamiento: 6
      vencida: 7
      por-vencer: 8
      resumen-diario: 9
      reporte-semanal: 10
      alertas-criticas: 11

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    studio.devbyjose.healthyme_reclamaciones: INFO
    org.hibernate.SQL: WARN