server:
  port: 8090
  shutdown: graceful

spring:
  application:
    name: healthyme-notification
  jackson:
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: non_null
    property-naming-strategy: SNAKE_CASE
    time-zone: America/Lima
  datasource:
    url: jdbc:mysql://mysql:3306/healthyme_notification?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: j0s33nr1qu3
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: alfred.asistente.soporte@gmail.com
    password: pplg hffd asbt evpp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connection-timeout: 5000
          timeout: 5000
          write-timeout: 5000
  thymeleaf:
    prefix: file:/app/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: true
    check-template: false
    check-template-location: false
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: notification-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
    instances:
      emailService:
        baseConfig: default
      medicoService:
        baseConfig: default
      pacienteService:
        baseConfig: default

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    studio.devbyjose.healthyme_notification: INFO
    org.springframework.mail: WARN
    org.apache.kafka: WARN