spring:
  application:
    name: healthyme-laboratorio
  jackson:
    default-property-inclusion: non_null
    property-naming-strategy: SNAKE_CASE
    time-zone: America/Lima
    serialization:
      write-dates-as-timestamps: false
    date-format: yyyy-MM-dd HH:mm:ss
  datasource:
    url: jdbc:mysql://mysql:3306/healthyme_laboratorio?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: j0s33nr1qu3
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  thymeleaf:
    prefix: file:/app/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: true
    check-template: false
    check-template-location: false

server:
  port: 8087
  shutdown: graceful

feign:
  client:
    config:
      default:
        connect-timeout: 5000
        read-timeout: 10000

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    dev.choco.healthyme_laboratorio: INFO
    org.springframework.web: WARN
    org.hibernate: WARN