spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME:healthyme_storage_prod}
    username: ${DB_USER_PROD}
    password: ${DB_PASSWORD_PROD}
    hikari:
      maximum-pool-size: 15
      minimum-idle: 5
      idle-timeout: 300000
      max-lifetime: 1200000
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 15MB

storage:
  location: ${STORAGE_LOCATION:/mnt/storage/healthyme/files}
  max-capacity-mb: 102400  # 100GB para producción
  allowed-content-types: >
    image/jpeg,image/png,image/gif,application/pdf,
    application/msword,application/vnd.openxmlformats-officedocument.wordprocessingml.document,
    application/vnd.ms-excel,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet

logging:
  level:
    root: WARN
    studio.devbyjose: INFO
    org.springframework: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: /var/log/healthyme/storage.log
    max-size: 25MB
    max-history: 14

resilience4j:
  circuitbreaker:
    instances:
      fileOperationBreaker:
        failureRateThreshold: 40
        waitDurationInOpenState: 30s
        slidingWindowSize: 20
      dbOperationBreaker:
        failureRateThreshold: 30
        waitDurationInOpenState: 60s