spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:healthyme_storage_dev}?createDatabaseIfNotExist=true
    username: ${DB_USER_DEV}
    password: ${DB_PASSWORD_DEV}
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

storage:
  location: ./storage/files
  max-capacity-mb: 2048

logging:
  level:
    root: INFO
    studio.devbyjose: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG

resilience4j:
  circuitbreaker:
    instances:
      fileOperationBreaker:
        failureRateThreshold: 70
      dbOperationBreaker:
        failureRateThreshold: 70