spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME:healthyme_consultas_prod}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect

  jackson:
    default-property-inclusion: non_null
    property-naming-strategy: SNAKE_CASE
    time-zone: America/Lima

  kafka:
    bootstrap-servers: localhost:9092

server:
  port: ${PORT}

logging:
  level:
    root: INFO
    dev.Elmer: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG

resilience4j:
  circuitbreaker:
    instances:
      recetaService:
        waitDurationInOpenState: 8s
        failureRateThreshold: 60
      pacienteService:
        waitDurationInOpenState: 6s
        failureRateThreshold: 60
      medicoService:
        waitDurationInOpenState: 6s
        failureRateThreshold: 60

  timelimiter:
    instances:
      recetaService:
        timeoutDuration: 5s
      pacienteService:
        timeoutDuration: 5s
      medicoService:
        timeoutDuration: 5s

  retry:
    instances:
      recetaRetry:
        maxAttempts: 3
        waitDuration: 1s
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2