spring:
  application:
    name: security-service
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: false
  datasource:
    url: jdbc:mysql://mysql:3306/healthyme_security?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: j0s33nr1qu3
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
    data: classpath:script.sql
    sql:
      init:
        mode: always
        continue-on-error: false
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
  jackson:
    property-naming-strategy: SNAKE_CASE
    time-zone: America/Lima
    serialization:
      write-dates-as-timestamps: false
    date-format: yyyy-MM-dd HH:mm:ss
  # Configuración OAuth2
  security:
    oauth2:
      authorizationserver:
        issuer: http://security-service:8085/auth

server:
  port: 8085
  shutdown: graceful

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    studio.devbyjose.security_service: INFO
    org.springframework.security: WARN
    org.hibernate.SQL: WARN